# Generated by Django 5.2.4 on 2025-09-30 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatConversation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Conversation",
                "verbose_name_plural": "Chat Conversations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("user", "User Message"),
                            ("assistant", "Assistant Message"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("sources", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="analysis.chatconversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MarketReport",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("analysis_id", models.CharField(max_length=100, unique=True)),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard Analysis"),
                            ("deep", "Deep Analysis"),
                            ("quick", "Quick Analysis"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("industry", models.CharField(max_length=100)),
                ("target_market", models.CharField(max_length=100)),
                ("website", models.URLField(blank=True, null=True)),
                ("current_positioning", models.TextField(blank=True)),
                ("brand_description", models.TextField(blank=True)),
                ("dashboard_data", models.JSONField(blank=True, default=dict)),
                ("detailed_scores", models.JSONField(blank=True, default=dict)),
                ("research_report", models.JSONField(blank=True, default=dict)),
                ("key_insights", models.JSONField(blank=True, default=list)),
                ("revenue_projections", models.JSONField(blank=True, default=dict)),
                ("recommended_actions", models.JSONField(blank=True, default=dict)),
                ("executive_summary", models.TextField(blank=True)),
                ("full_content", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Market Report",
                "verbose_name_plural": "Market Reports",
                "ordering": ["-created_at"],
            },
        ),
    ]
