# Generated by Django 4.2.7 on 2025-10-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketreport",
            name="annual_revenue",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="marketreport",
            name="budget_range",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="marketreport",
            name="company_size",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="marketreport",
            name="competitive_advantage",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketreport",
            name="current_markets",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="marketreport",
            name="customer_segment",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="marketreport",
            name="expansion_direction",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="marketreport",
            name="expansion_timeline",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="marketreport",
            name="funding_stage",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="marketreport",
            name="key_products",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketreport",
            name="partnership_preferences",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketreport",
            name="regulatory_requirements",
            field=models.TextField(blank=True, null=True),
        ),
    ]
