# Generated by Django 4.2.7 on 2025-10-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0002_marketreport_annual_revenue_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketreport",
            name="competitor_analysis",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="marketreport",
            name="segment_arbitrage",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
