# Generated by Django 5.1.3 on 2026-02-14 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0003_marketreport_competitor_analysis_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="marketreport",
            name="deep_dives",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="marketreport",
            name="playbook",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="MultiMarketReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("industry", models.CharField(max_length=100)),
                ("target_markets", models.JSONField(default=list)),
                ("comparison_matrix", models.JSONField(blank=True, default=dict)),
                ("ranking", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "individual_reports",
                    models.ManyToManyField(
                        blank=True,
                        related_name="multi_market_groups",
                        to="analysis.marketreport",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multi_market_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Multi-Market Report",
                "verbose_name_plural": "Multi-Market Reports",
                "ordering": ["-created_at"],
            },
        ),
    ]
