# Generated by Django 5.1.3 on 2026-02-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0004_marketreport_deep_dives_marketreport_playbook_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketreport",
            name="is_shared",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="marketreport",
            name="share_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
