# Generated by Django 4.2.7 on 2025-10-05 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_managers_user_google_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                (
                    "verification_type",
                    models.CharField(
                        choices=[
                            ("signup", "Sign Up"),
                            ("password_reset", "Password Reset"),
                            ("email_change", "Email Change"),
                        ],
                        default="signup",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["code"], name="accounts_em_code_eebfba_idx"),
                    models.Index(
                        fields=["user", "is_used"],
                        name="accounts_em_user_id_84251d_idx",
                    ),
                ],
            },
        ),
    ]
