# Generated by Django 5.1.3 on 2026-02-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_emailverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="analyses_used_this_period",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="billing_period_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("admin", "Admin")],
                default="user",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_tier",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("starter", "Starter"),
                    ("professional", "Professional"),
                    ("enterprise", "Enterprise"),
                ],
                default="free",
                max_length=20,
            ),
        ),
    ]
